#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the repo root; the Vercel project lives in apps/web.
cd "$(dirname "$0")/.."
WEB_DIR="apps/web"
ENV_FILE="$WEB_DIR/.env.local"

VERCEL=(vercel)
command -v vercel >/dev/null 2>&1 || VERCEL=(pnpm dlx vercel@latest)

vc() { (cd "$WEB_DIR" && "${VERCEL[@]}" "$@"); }

# set_vercel_env NAME VALUE writes NAME to every Vercel environment.
set_vercel_env() {
  local name="$1" value="$2" target ok=1
  for target in production preview development; do
    printf '%s' "$value" | vc env add "$name" "$target" --force >/dev/null 2>&1 || ok=0
  done
  if (( ok )); then
    printf '  %s✓ set%s Vercel env %s (production, preview, development)\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name (Project → Settings → Environment Variables)")
    warn "couldn't set Vercel env $name; add it in the dashboard"
  fi
}

TOTAL_STAGES=9

banner "Shazam: provision Vercel, Neon, Blob, ACRCloud and AudD"

stage "Vercel: sign in"
say "The Vercel CLI links this repo to a project and stores env variables."
note "Using: ${VERCEL[*]}"
if vc whoami >/dev/null 2>&1; then
  say "Already signed in as $(vc whoami 2>/dev/null | tail -n1)."
else
  step "A browser window will open; approve the CLI login."
  vc login
fi
pause

stage "Vercel: link the project"
say "Creates (or picks) the Vercel project for the web app and connects GitHub."
if [[ -f "$WEB_DIR/.vercel/project.json" ]]; then
  say "Already linked: $WEB_DIR/.vercel/project.json exists."
else
  step "Answer the prompts: your scope, 'Link to existing project?' → No, name it 'shazam'."
  step "When asked for the code directory, accept ./ (we're already inside $WEB_DIR)."
  vc link
fi
step "Now connect the GitHub repo so every push deploys (previews on PRs):"
vc git connect || warn "If that failed, connect it in Project → Settings → Git."
open_url "https://vercel.com/dashboard"
step "Open the project → Settings → Build and Deployment → Root Directory = apps/web → Save."
pause "Done setting the Root Directory?"

stage "Neon Postgres"
say "Lookups and Matches live in Neon Postgres from the Vercel Marketplace."
open_url "https://vercel.com/dashboard/stores"
step "Click 'Create Database' → choose Neon → Continue → accept the defaults (free plan)."
step "Connect it to the 'shazam' project for all environments."
note "Vercel then sets DATABASE_URL on the project automatically."
pause "Database created and connected?"

stage "Vercel Blob"
say "Audio Clips are staged briefly in Vercel Blob while a Lookup runs."
open_url "https://vercel.com/dashboard/stores"
step "Click 'Create Database' → choose Blob → name it 'shazam-clips' → Create."
step "Connect it to the 'shazam' project for all environments."
note "Vercel then sets BLOB_READ_WRITE_TOKEN on the project automatically."
pause "Blob store created and connected?"

stage "ACRCloud (primary recognition engine)"
say "ACRCloud matches Clips against its music catalogue."
open_url "https://console.acrcloud.com/"
step "Sign up / sign in (the free trial is fine)."
step "Go to Audio & Video Recognition → Projects → Create Project."
step "Audio source: 'Recorded Audio'. Buckets: tick 'ACRCloud Music'. Create."
step "Open the project: copy Host, Access Key and Access Secret."
note "(Console labels drift; look for the three credentials on the project page.)"
ask ACRCLOUD_HOST "Host (e.g. identify-eu-west-1.acrcloud.com):"
ACRCLOUD_HOST="${ACRCLOUD_HOST#https://}"; ACRCLOUD_HOST="${ACRCLOUD_HOST%/}"
ask ACRCLOUD_ACCESS_KEY "Access Key:"
ask_secret ACRCLOUD_ACCESS_SECRET "Access Secret:"
write_env ACRCLOUD_HOST "$ACRCLOUD_HOST"
write_env ACRCLOUD_ACCESS_KEY "$ACRCLOUD_ACCESS_KEY"
write_env ACRCLOUD_ACCESS_SECRET "$ACRCLOUD_ACCESS_SECRET"
set_vercel_env ACRCLOUD_HOST "$ACRCLOUD_HOST"
set_vercel_env ACRCLOUD_ACCESS_KEY "$ACRCLOUD_ACCESS_KEY"
set_vercel_env ACRCLOUD_ACCESS_SECRET "$ACRCLOUD_ACCESS_SECRET"
pause

stage "AudD (fallback recognition engine)"
say "AudD is asked only about Clips ACRCloud couldn't match."
open_url "https://dashboard.audd.io/"
step "Sign up / sign in; your API token is shown on the dashboard. Copy it."
ask_secret AUDD_API_TOKEN "AudD API token:"
write_env AUDD_API_TOKEN "$AUDD_API_TOKEN"
set_vercel_env AUDD_API_TOKEN "$AUDD_API_TOKEN"
pause

stage "Engine order and Extractor secret"
say "RECOGNITION_ENGINES lists engines in order: primary first, then fallbacks."
ask RECOGNITION_ENGINES "Engine order [acrcloud,audd]:"
RECOGNITION_ENGINES="${RECOGNITION_ENGINES:-acrcloud,audd}"
write_env RECOGNITION_ENGINES "$RECOGNITION_ENGINES"
set_vercel_env RECOGNITION_ENGINES "$RECOGNITION_ENGINES"
say "EXTRACTOR_SECRET stops strangers calling the media Extractor directly."
EXTRACTOR_SECRET=$(_existing EXTRACTOR_SECRET || true)
[[ -n "$EXTRACTOR_SECRET" ]] || EXTRACTOR_SECRET=$(openssl rand -hex 32)
write_env EXTRACTOR_SECRET "$EXTRACTOR_SECRET"
set_vercel_env EXTRACTOR_SECRET "$EXTRACTOR_SECRET"
pause

stage "Optional: cookies and proxy for blocked platforms"
say "Skip all of these at launch: with none set the Extractor behaves as normal."
say "Come back only when Lookups start failing with 'blocked' (the platform is"
say "refusing downloads from Vercel's servers). Re-run this wizard to add them."
echo
step "YTDLP_YOUTUBE_COOKIES: Netscape cookies.txt for youtube.com"
note "1. In a private window, sign in to YouTube with a spare Google account."
note "2. Export youtube.com cookies with the 'Get cookies.txt LOCALLY' extension."
note "3. Close the private window without signing out, so the cookies stay valid."
step "YTDLP_INSTAGRAM_COOKIES: Netscape cookies.txt for instagram.com"
warn "Use a throwaway Instagram account, NEVER your personal one:"
warn "automated downloads can get the account flagged or banned."
note "Sign in to the burner account and export instagram.com cookies the same way."
step "YTDLP_PROXY: a proxy every download goes through"
note "e.g. http://user:pass@proxy.example:8080 from a residential proxy provider."
note "Use it if cookies alone don't get past the block."
echo
set_cookies() {
  local name="$1" file=""
  confirm "Set $name from a cookies.txt file now?" || return 0
  printf '  %sPath to cookies.txt:%s ' "$BOLD" "$RESET"
  read -r file || true
  file="${file/#\~/$HOME}"
  if [[ ! -f "$file" ]]; then
    warn "no file at '$file'; skipped $name"
    SKIPPED+=("$name (re-run the wizard with a cookies.txt file)")
    return 0
  fi
  set_vercel_env "$name" "$(cat "$file")"
  # .env.local values are single-line; the Extractor turns \n back into newlines.
  write_env "$name" "$(awk '{printf "%s\\n", $0}' "$file")"
}
set_cookies YTDLP_YOUTUBE_COOKIES
set_cookies YTDLP_INSTAGRAM_COOKIES
ask YTDLP_PROXY "Proxy URL [blank to skip]:"
if [[ -n "$YTDLP_PROXY" ]]; then
  write_env YTDLP_PROXY "$YTDLP_PROXY"
  set_vercel_env YTDLP_PROXY "$YTDLP_PROXY"
fi
note "To switch one off later: vercel env rm <NAME> production preview development"
pause

stage "Pull env, migrate the database, deploy"
say "Pulling every Vercel env variable (incl. DATABASE_URL, BLOB_READ_WRITE_TOKEN) locally."
vc env pull .env.local --yes || warn "env pull failed; re-run: cd $WEB_DIR && vercel env pull .env.local"
if confirm "Apply database migrations to Neon now?"; then
  pnpm --filter @shazam/drizzle db:migrate || warn "migration failed; run: pnpm --filter @shazam/drizzle db:migrate"
fi
say "Push to main (or open a PR) and Vercel deploys automatically."
note "Local dev: pnpm dev  (the Extractor runs via: pnpm --filter web dev:extractor)"
pause

finish
